create_body: {
    "attributes": {
        "FIRSTNAME": "Cristhian1111",
        "LASTNAME": "Vargas1111111"
    },
    "listIds": [
            14
    ],
    "updateEnabled": false,
    "email": "cristian_vargas11111@ApiTesting.com",
    "ext_id": "10111",
    "emailBlacklisted": false,
    "smsBlacklisted": false
}
