no_password_message: "Missing parameter(s): password"
no_username_message: "Missing parameter(s): username"
no_email_message: "Missing parameter(s): email"
not_found: "No route was found matching the URL and request method."
username_existing: "Sorry, that username already exists!"
email_existing: "Sorry, that email address is already used!"
invalid_id_message: "Invalid user ID."
invalid_email: "Invalid email address."
username_not_editable: "Username is not editable."
invalid_parent: {"code":"rest_term_invalid","message":"Parent term does not exist.","data":{"status":400}}
body_no_username: {"password":"password","email":"email@at19.com"}
body_no_password: {"username":"username","email":"email@at19.com"}
body_no_email: {"username":"username","password":"password"}
default_role: 'subscriber'
username_61_characters:  'characterscharacterscharacterscharacterscharacterscharacters1'
username_to_long: 'Username may not be longer than 60 characters.'
email_invalid_format: 'noformatmail'
invalid_parameter_email: 'Invalid parameter(s): email'
no_reassign_user: 'Missing parameter(s): reassign'
username_invalid_characters: 'username*+'
invalid_parameter_username: 'Invalid parameter(s): username'
