no_password_message: "Missing parameter(s): password"
no_username_message: "Missing parameter(s): username"
no_email_message: "Missing parameter(s): email"
not_found: "No route was found matching the URL and request method."
username_existing: "Sorry, that username already exists!"
email_existing: "Sorry, that email address is already used!"
invalid_id_message: "Invalid user ID."
invalid_email: "Invalid email address."
username_not_editable: "Username is not editable."
body_no_username: {"password":"password","email":"email@at19.com"}
body_no_password: {"username":"username","email":"email@at19.com"}
body_no_email: {"username":"username","password":"password"}
default_role: 'subscriber'
username_61_characters:  'characterscharacterscharacterscharacterscharacterscharacters1'
username_to_long: 'Username may not be longer than 60 characters.'
email_invalid_format: 'noformatmail'
invalid_parameter_email: 'Invalid parameter(s): email'
no_reassign_user: 'Missing parameter(s): reassign'
username_invalid_characters: 'username*+'
invalid_parameter_username: 'Invalid parameter(s): username'
ignore: ['username', 'first_name', 'last_name', 'email', 'locale', 'nickname', 'roles', 'registered_date', 'capabilities', 'extra_capabilities', 'meta']
invalid_parent: "Parent term does not exist."
empty_parent: "Invalid parameter(s): parent"
non_existent_id: "Term does not exist."
empty_name: "A name is required for this term."
delete_without_force: "Terms do not support trashing. Set 'force=true' to delete."
default_category: "Sorry, you are not allowed to delete this term."
category_without_name: "Missing parameter(s): name"
